import Head from "next/head"

export default function Grid() {
    return(
        <>
        <Head>
        <title>Grid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            Grid
        </div>
        </>
    )
}