import Head from 'next/head';
import { useEffect, useState } from 'react';
import ImagePath from '../components/ImagePath';

export default function Home() {
  const [image, setImage] = useState([]);
  useEffect(() => {
    const fetchImages = async () => {
      const response = await fetch(
        `https://api.unsplash.com/photos?client_id=${process.env.NEXT_PUBLIC_CLIENT_ID}`
      );
      const data = await response.json();
      setImage(data);
      console.log(data);
      setImage(data);
    };
    fetchImages();
  }, []);

  return (
    <div>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-100 h-screen">
        {!image ? (
          <p className='font-bold text-4xl flex items-center justify-center h-screen'>Loading...</p>
        ) : (
          <div className="p-5 container mx-auto">
            <p className="flex text-xl sm:text-2xl md:text-4xl font-bold mb-5 md:my-5 text-slate-800">
              Recommended For You
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 ">
              {image.map((image, index) => (
                <ImagePath key={index} {...image} />
              ))}
            </div>
          </div>
        )}
        <p className='text-center mt-4 text-sm'>Made with ❤ by <a href='www.twitter.com/aiiomide' className='text-purple-500'>AioLabs</a></p>
      </div>
    </div>
  );
}
